spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: `{cipher}5f2ec696aaff1117713bb77bdca68ada7f272b1216596bcddbf5cb399cb5bfcb`
    driver-class-name: org.h2.Driver

token:
  #  expiration milli-seconed 60 * 60 * 24 * 1000 = one day
  expiration_time: 86400000
  secret: user_token_dev_changed

gateway:
  ip: 192.168.219.102