spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA56lBFSlTctaI+RPtXdu2XLO2fixZfKiRQBstr5Za3NUZ/wjmgSrFKcXcsYILxDR3UY6YK+CrK6O1zVW9UOlOUxvsjsTnOuHDjDiZZrWwDmgTcTwN96os4qLl46GIepfqGM1hB2mIeGOAO+CJ4VnwBqwrn9nVXiPpzctr8d/tD34nah9lrgKqWgQms6RFJ0LW6rZjJdsh4q7po1PxNdfmC+V3sg21KJ+hS4TwzIzMixtlYJ1Pj3ap4rwRShMaV2ZnTMb7bU1512BFfj8pbpEgYUq+P1WkhbqjWXyOkaI14YZQPzEU7FR7WG041WrnWumSHv4LE/1L5Mq4rHVtnYmuiFrGQsXwvIBw+Q2dllP02C3ZCkZBfNzghcvd++Oa73Fc='
    driver-class-name: org.h2.Driver

token:
  #  expiration milli-seconed 60 * 60 * 24 * 1000 = one day
  expiration_time: 86400000
  secret: '{cipher}AQAwEasJd9VRUaXCLFVqGV+x0n1Y81UAjfCjF5ect3u+mCinFW7Zf6pXN/agAbyWf8dnVWd0XneOMcTSglv/WhOUOtByltn6TGP7MkF0wmUQjvW4w3a6IOkt1gL8UHX+pBaIrUiulM5ndeGZeqKN6On59AbBDvHGzd/domTwvrAT89Me+pA4Crvyb9e4faLwyIWA5PLO/J7xua9eaoiyGWXMHdywSWWut6gzc1FWPOKqnsMHxcJHFbdE/wsBqPYkm5WxQqwoCv+zrkdp3vWJ3s1sWushIC7DKxvacHJdjqierPMrAwsC/32tPVL1cyp9nD2L5zHcenoyWhXrgZA31AlWOyZqtHPuXFqHCbj6g0r452mzmOLlLMEJOo+5Ln03OTs='


gateway:
  ip: 192.168.219.102

# if RestTamplate Bean @LoadBalanced ==> 127.0.0.1:8000 => order-service
order_service:
#  url: http://127.0.0.1:8000/order-service/%s/orders
  url: http://order-service/order-service/%s/orders