spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA56lBFSlTctaI+RPtXdu2XLO2fixZfKiRQBstr5Za3NUZ/wjmgSrFKcXcsYILxDR3UY6YK+CrK6O1zVW9UOlOUxvsjsTnOuHDjDiZZrWwDmgTcTwN96os4qLl46GIepfqGM1hB2mIeGOAO+CJ4VnwBqwrn9nVXiPpzctr8d/tD34nah9lrgKqWgQms6RFJ0LW6rZjJdsh4q7po1PxNdfmC+V3sg21KJ+hS4TwzIzMixtlYJ1Pj3ap4rwRShMaV2ZnTMb7bU1512BFfj8pbpEgYUq+P1WkhbqjWXyOkaI14YZQPzEU7FR7WG041WrnWumSHv4LE/1L5Mq4rHVtnYmuiFrGQsXwvIBw+Q2dllP02C3ZCkZBfNzghcvd++Oa73Fc='
    driver-class-name: org.h2.Driver

token:
  #  expiration milli-seconed 60 * 60 * 24 * 1000 = one day
  expiration_time: 86400000
  secret: user_token_user-service

gateway:
  ip: 192.168.219.102